// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Petshop.Models;

#nullable disable

namespace Petshop.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Petshop.Models.Animal", b =>
                {
                    b.Property<int>("idAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAnimal"));

                    b.Property<string>("nome")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipoAnimal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idAnimal");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Petshop.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("idCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Petshop.Models.Servico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoServicoId")
                        .HasColumnType("int");

                    b.Property<int>("animalId")
                        .HasColumnType("int");

                    b.Property<string>("horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idAnimal")
                        .HasColumnType("int");

                    b.Property<int?>("idCliente")
                        .HasColumnType("int");

                    b.Property<int?>("idTipoServico")
                        .HasColumnType("int");

                    b.Property<float>("valorTotal")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("idAnimal");

                    b.HasIndex("idCliente");

                    b.HasIndex("idTipoServico");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Petshop.Models.TipoServico", b =>
                {
                    b.Property<int>("idTipoServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoServico"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idTipoServico");

                    b.ToTable("TipoServicos");
                });

            modelBuilder.Entity("Petshop.Models.Servico", b =>
                {
                    b.HasOne("Petshop.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("idAnimal");

                    b.HasOne("Petshop.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("idCliente");

                    b.HasOne("Petshop.Models.TipoServico", "TipoServico")
                        .WithMany()
                        .HasForeignKey("idTipoServico");

                    b.Navigation("Animal");

                    b.Navigation("Cliente");

                    b.Navigation("TipoServico");
                });
#pragma warning restore 612, 618
        }
    }
}
